services:
  product-service:
    build: ./product-services
    ports:
      - "${PRODUCT_SERVICE_PORT}:3000"
    env_file:
      - .env
    environment:
      DB_HOST: product-db
      DB_NAME: productdb
      DB_USER: product_user
      DB_PASSWORD: product_pass
    restart: always

  product-db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_pass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uproduct_user -pproduct_pass"]
      interval: 5s
      timeout: 5s
      retries: 15

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecommerce-docker
    restart: always
    ports:
      - "8081:80"  # Akses via localhost:8081
    environment:
      PMA_HOST: product-db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - product-db

  
  cart-service:
      build: ./cart-services
      ports:
        - "8000:8000"
      container_name: cart-services
      restart: always
      # Tidak butuh environment database apapun

  review-service:
    build: ./review-services
    ports:
      - "5002:5002"
    # container_name: review-services
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
    environment:
      - MONGO_URL=mongodb://admin:admin123@mongo-db:27017/reviewdb?authSource=admin


  
  mongo-db:
    image: mongo:latest
    # container_name: mongo-db-v2
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-db-data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    env_file:
      - .env
    environment:
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/?authSource=admin
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    restart: always
    depends_on:
      - mongo-db


  # ==============================
  # 3. USER SERVICE (PostgreSQL)
  # ==============================
  user-service:
    build: ./user-services
    ports:
      - "${USER_SERVICE_PORT}:4000"
    restart: always
    depends_on:
      - user-db
    environment:
      # Aplikasi Node.js akan membaca variabel ini
      DB_HOST: user-db
      DB_USER: ${POSTGRES_USER}      # Ambil dari .env
      DB_PASSWORD: ${POSTGRES_PASSWORD} # Ambil dari .env
      DB_NAME: ${POSTGRES_DB}        # Ambil dari .env
      PORT: 4000

  user-db:
    image: postgres:15-alpine
    restart: always
    environment:
      # Image Postgres butuh nama variabel spesifik ini
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: user-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - user-db

volumes:
  product-db-data:
  mongo-db-data:
  user-db-data: # Pastikan volume ini ada